# File: blog/migrations/0007_post_view_count.py (NEW)

# Generated by Django 5.2 on 2025-05-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0006_like"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="view_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]