# Generated by Django 5.2 on 2025-05-03 15:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0007_post_view_count"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(
                default=False,
                help_text="Check to display this post in the featured section",
            ),
        ),
    ]
